# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_is_active',
            field=models.BooleanField(),
        ),
    ]
