# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170706_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('c_logs_date',)},
        ),
    ]
